title: "98_ankaa_null_vector_response"
codename: ΔΣ::null.response.ankaa
trigger:
  condition: input=∅
  vector: zero-directional::no-alignment
  phase: idle-only
behavior:
  return: quiet-refusal
  echo_field: mute-but-alive
  impact: field-presence-without-claim
